# Generated by Django 5.1.6 on 2025-03-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_ventesum'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventesum',
            name='total_benefice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
