# Generated by Django 5.1.6 on 2025-03-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenteSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ventes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
    ]
