# Generated by Django 5.1.6 on 2025-03-05 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0002_ventesum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VenteSum',
        ),
    ]
